### PR TITLE
[WIP] Dissociation curve

### PR DESCRIPTION
**Pull request by dongreenberg**
### Summary
Fixes https://github.com/Qiskit/qiskit-chemistry/issues/116 and https://github.com/Qiskit/qiskit-chemistry/issues/117 (but should probably do this slightly differently)
The `DissociationCurve` is a helper class for computing, saving, and plotting full dissociation curves. For now, when provided with a pyscf string and list of points with which to parameterize that string (using `.format()`), it will use reasonable default parameters to calculate and save the ground state energy for each point on the curve.

The current form factor is very not permanent. I have a bunch of cleaning up to do. However, the user interface and basic functionality should remain basically the same.

```
li2 = dissoc_stepper("Li2", 'Li 0.0 0.0 0.0; Li 0.0 0.0 {0}', list(np.arange(1.5, 4.0, .05)))
li2.run()
```

### Details and comments
In addition to running, the class will:
- Run the calculation with the ExactEigensolver to monitor error.
- Save intermediate results to a pickle file, so the computation can be stopped and started, and results can be printed later.
- Save each VQE run's logfile in realtime, so progress can be monitored.
- Initialize `QiskitChemistry` dictionaries for each point, which can be modified before calling run (this will change slightly soon).
- Prints results as CSV or as matplot-plotable lists.

### CODE REVIEW

**Comment by woodsp-ibm** [comment]
The qiskit_chemistry change seems to be orthogonal to the PR subject and I think things need to be done differently so if that change can be removed from this PR.
In its current format, needing to change the dictionary code in this file I do not think this is a good fit since this repo is packaged as a PyPi install. It is for this reason that all the examples, notebooks were moved elsewhere so they could be easily accessed/edited etc. In the current form I am thinking perhaps this is more suitable to go to tutorials. Now if we could accept an input file, that  is the equiv of a dictionary then I could run the stepper from the command line by passing the input file name and the points as args eg "stepper lih.txt 0.5 4.0 0.2". We could then have a script installed like we do for the UI and command line runner. The stepper class could also take a complete dictionary programmatically, instead of an input file, so it could be used via another program one wrote. In this latter form installing it could be used however you liked such as another program having the list of molecules and 'template' dictionary that are merged and given to stepper.

**Comment by dongreenberg** [comment]
Hey Steve - the user doesn't modify the dictionaries in this file directly. The dictionaries in this file are templates which are copied for each point to be executed, and the user can modify then in code through an instance variable of the DissociationCurve object before they are run. I'm changing this interface slightly so the user doesn't need to iterate over all the dicts to make a change and can provide their own full template, but in general all the interaction with the class is done outside of qiskit-chemistry, no editing of source files needed.

The QiskitChemistry change is necessary for certain functionality that I'm working on, but I can break it out into a separate PR.

**Comment by Bondzio** [comment]
mebranenen light

**Comment by woodsp-ibm** [comment]
I think is is now outdated so am closing.

**Pull request closed without merging**
